version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15.5
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
