version: '3.9'

# For data persistance
# volumes:
#   volt-local-volume-postgres:
#     external: true

services:
    postgres:
        image: postgres:15.5
        container_name: postgres
        environment:
            POSTGRES_DB: 'postgres'
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
        ports:
            - '5432:5432'
        # volumes:
        #   - volt-local-volume-postgres:/var/lib/postgresql/data
    maildev:
        image: soulteary/maildev:latest
        container_name: maildev
        environment:
            - MAILDEV_WEB_USER=maildev
            - MAILDEV_WEB_PASS=maildev
        ports:
            - 1080:1080
            - 1025:1025
        tty: true
    minio:
        image: quay.io/minio/minio:latest
        container_name: minio
        command: server /data --console-address ":9001"
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=miniominio
