/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Sat, 27 Jan 2024 13:31:26 GMT
///
/// Parent module: authModule
/// Controller: "authController" registered as "auth" (1 routes)

import { request } from '../central';
import type { SignInResponse } from '../_types/src/lib/modules/auth/interfaces/auth.interfaces';
import type { SignInDTO } from '../_types/src/lib/modules/auth/interfaces/auth.dtos';

export default {
  // POST @ /auth/signIn
  signIn(params: {}, body: SignInDTO, query: {} = {}): Promise<SignInResponse> {
    return request('POST', `/auth/signIn`, body, query);
  },
};
