/// Auto-generated file (nest-sdk-generator)
/// Please do not edit this file - re-generate the SDK using the generator instead.
/// Generated on: Sat, 27 Jan 2024 13:31:26 GMT
///
/// Module name: authModule

export { default as authController } from './authController';
